# Generated by Django 3.1.5 on 2021-01-07 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.IntegerField(blank=True, null=True, verbose_name='Final price')),
                ('final_amount', models.IntegerField(blank=True, null=True, verbose_name='Total amount')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Global category name')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Product description')),
                ('price', models.PositiveIntegerField(verbose_name='Product price')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('stars', models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True, verbose_name='Rating')),
                ('state', models.CharField(choices=[('solid', 'Solid'), ('liquid', 'Liquid'), ('gas', 'Gas')], max_length=255, verbose_name='State')),
                ('formula', models.CharField(max_length=100, verbose_name='Formula')),
                ('reagent_type', models.CharField(choices=[('acid', 'Acid'), ('bromide', 'Bromide'), ('alkali', 'Alkali'), ('halogens', 'Halogens')], max_length=255, verbose_name='Type of reagent')),
                ('conc', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Concentration')),
                ('weight', models.CharField(max_length=32, verbose_name='Weight')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Labware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Product description')),
                ('price', models.PositiveIntegerField(verbose_name='Product price')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('stars', models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True, verbose_name='Rating')),
                ('material', models.CharField(max_length=255, verbose_name='Material')),
                ('pack', models.BooleanField(default=False, verbose_name='Pack')),
                ('pack_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount of products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Product category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GolfClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Product description')),
                ('price', models.PositiveIntegerField(verbose_name='Product price')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('stars', models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True, verbose_name='Rating')),
                ('material', models.CharField(max_length=100)),
                ('flex', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Product category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirearmWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Product description')),
                ('price', models.PositiveIntegerField(verbose_name='Product price')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('stars', models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True, verbose_name='Rating')),
                ('caliber', models.CharField(max_length=50, verbose_name='Caliber')),
                ('action', models.CharField(choices=[('auto', 'Auto'), ('bolt', 'Bolt')], max_length=100, verbose_name='Action')),
                ('weight', models.CharField(max_length=32, verbose_name='Weight')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Product category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(verbose_name='Phone number')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='global_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.globalcategory', verbose_name='To global category'),
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('total_price', models.PositiveIntegerField(verbose_name='Total price')),
                ('to_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Customer')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Owner'),
        ),
        migrations.CreateModel(
            name='BowWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Product description')),
                ('price', models.PositiveIntegerField(verbose_name='Product price')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('stars', models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True, verbose_name='Rating')),
                ('weight', models.CharField(max_length=32, verbose_name='Weight')),
                ('arrow_speed', models.IntegerField(verbose_name='Arrow speed')),
                ('draw_length', models.CharField(max_length=50, verbose_name='Draw length')),
                ('brace_height', models.IntegerField(verbose_name='Brace height')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Product category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
