# Generated by Django 3.1.5 on 2021-01-07 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Product category'),
        ),
        migrations.AlterField(
            model_name='bowweapon',
            name='brace_height',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Brace height'),
        ),
        migrations.AlterField(
            model_name='bowweapon',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Product category'),
        ),
        migrations.AlterField(
            model_name='bowweapon',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price'),
        ),
        migrations.AlterField(
            model_name='bowweapon',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bowweapon',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='firearmweapon',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Product category'),
        ),
        migrations.AlterField(
            model_name='firearmweapon',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price'),
        ),
        migrations.AlterField(
            model_name='firearmweapon',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='firearmweapon',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='globalcategory',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='golfclub',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Product category'),
        ),
        migrations.AlterField(
            model_name='golfclub',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price'),
        ),
        migrations.AlterField(
            model_name='golfclub',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='golfclub',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='labware',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Product category'),
        ),
        migrations.AlterField(
            model_name='labware',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price'),
        ),
        migrations.AlterField(
            model_name='labware',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='labware',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='conc',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Concentration'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Rating'),
        ),
    ]
