# Generated by Django 3.1.5 on 2021-01-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210108_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='conc',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Concentration'),
        ),
    ]
