# Generated by Django 3.1.5 on 2021-01-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210108_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firearmweapon',
            name='action',
            field=models.CharField(choices=[('auto', 'Auto'), ('bolt', 'Bolt'), ('semi-automatic', 'Semi-Automatic'), ('pump', 'Pump')], max_length=100, verbose_name='Action'),
        ),
    ]
