# Generated by Django 3.1.4 on 2021-01-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210114_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product_slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
