# Generated by Django 3.1.4 on 2021-01-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210114_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Total price'),
        ),
    ]
