# Generated by Django 3.1.4 on 2021-01-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ManyToManyField(to='mainapp.Customer'),
        ),
    ]
