# Generated by Django 3.1.4 on 2021-01-15 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.TimeField(auto_created=True, auto_now=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer'),
        ),
    ]
