# Generated by Django 3.1.4 on 2021-01-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210115_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'MNew'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered')], default='new', max_length=50),
        ),
    ]
